### ISSUE TITLE
Vault Problem

### ISSUE THREAD

**Issue by LindAn79** [le-zoo/stonks#1]
![Screenshot_3](https://user-images.githubusercontent.com/49753879/180092344-95058e2a-6bd9-4c5c-a9fc-97c27668e372.png)
![Screenshot_4](https://user-images.githubusercontent.com/49753879/180092349-137aeb04-1444-40ab-8ddf-959c58c506ad.png)
![Screenshot_5](https://user-images.githubusercontent.com/49753879/180092667-e49c5630-f8d9-46ca-9e34-767675d859b5.png)

**Comment by Guillaumemartinfesta** [comment]
CMI doesn't have Vault support so the problem doesn't come from Stonks you can try using the CMI injetor plugin as specified in 
https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/
