### ISSUE TITLE
Display board is broken when restart

### ISSUE THREAD

**Issue by mfcc168** [le-zoo/stonks#10]
![image](https://user-images.githubusercontent.com/88373848/211968210-75995c57-a838-49ad-9cc9-55be3ceaf7a8.png)

**Comment by Guillaumemartinfesta** [comment]
I will treat this bug (No need to make a 1 star review for it tho ;( )

**Comment by Guillaumemartinfesta** [comment]
This issue should be fixed by now, if you still encounter this issue you can talk about it in the discord channel.
