### ISSUE TITLE
Why is the word on the board blurry?

### ISSUE THREAD

**Issue by PEK-ZBAA** [le-zoo/stonks#2]
Hello author, I purchased the plugin you wrote yesterday on SpigotMC and have found a problem so far. You see, why aren't the words on my board very clear? I see that the words on your wiki are still very clear. I see other clothes on the Internet also very clearly.

**Comment by PEK-ZBAA** [comment]
<img width="849" alt="屏幕截图 2022-08-01 094432" src="https://user-images.githubusercontent.com/71160034/182056950-e9443249-4eb9-4490-964a-1b8e8842a630.png">
This is the situation in my server, very unclear

**Comment by PEK-ZBAA** [comment]
This is the picture you put in the wiki and it looks very clear.
<img width="439" alt="image" src="https://user-images.githubusercontent.com/71160034/182057059-bad3a1ca-b5c0-4936-a438-42c369f67c00.png">

**Comment by PEK-ZBAA** [comment]
This is what I saw on another server, and they translated it into Chinese, the font is still very clear.
![a1996c591984eebda5c6ffbe8b3a19a](https://user-images.githubusercontent.com/71160034/182057307-805a9eeb-3ff7-4bcd-b0ba-58213696d717.jpg)

**Comment by PEK-ZBAA** [comment]
I translated the title as Chinese, it's still vague.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/71160034/182057830-f3672ee9-0bbf-4ec0-a2d0-8a013895f878.png">

**Comment by PEK-ZBAA** [comment]
Author, how to solve this problem?

**Comment by Indyuce** [comment]
Have you tried changing the settings of your shaders pack
