### ISSUE TITLE
I hope the author adds more features

### ISSUE THREAD

**Issue by PEK-ZBAA** [le-zoo/stonks#3]
Author, this is a very good plugin and I love it. But I also hope you can add some new features and I hope you can change the appearance of board.Here are my suggestions:
1. Can you add a limit on the number of leverage in the config file? Players in my server always increase the leverage value to at least 100,000, and at least once buy 10 shares. After players buy it, the stock will skyrocket.Players will sell it again, and they can make a lot of money at a time, resulting in some imbalance in the server economy.
2. Can you change the word that appears on the display board? Make it appear clearer. In the version 1.0.3, the words on the board are very vague and unclear in the case of a height of 3, and it looks a little uncomfortable.
I hope you will adopt and implement the two suggestions written above, thank you very much!

**Comment by Guillaumemartinfesta** [comment]
I made the limitation for the leverage in the config. I added some config to change the font size & style for the boards. But what is exactly your suggestion for the appareance of the board? You want the words to be bigger ?

**Comment by Guillaumemartinfesta** [comment]
I applied these changes hope you also find it more readable.
