### ISSUE TITLE
Console errors when attempting to generate displays on 1.19.1

### ISSUE THREAD

**Issue by ubermidas** [le-zoo/stonks#4]
Hello, 

We've been testing this plugin in our server and we are experiencing console errors when attempting to generate displays on 1.19.1. I realize this is not an plugin-supported Minecraft version. Here's the output when attempting to create a board:

> 05.08 15:45:39 [Server] INFO supermidas issued server command: /stonks display board create ahjin day 3 3
05.08 15:45:40 [Server] ERROR null
05.08 15:45:40 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'stonks' in plugin Stonks v1.0.4
05.08 15:45:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
05.08 15:45:40 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
05.08 15:45:40 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:40 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:40 [Server] INFO at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.1.jar:?]
05.08 15:45:40 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
05.08 15:45:40 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:290) ~[?:?]
05.08 15:45:40 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2295) ~[?:?]
05.08 15:45:40 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2249) ~[?:?]
05.08 15:45:40 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
05.08 15:45:40 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
05.08 15:45:40 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:40 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
05.08 15:45:40 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
05.08 15:45:40 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:40 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:40 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
05.08 15:45:42 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:42 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:42 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
05.08 15:45:42 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1463) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:42 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:42 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:42 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
05.08 15:45:42 [Server] INFO Caused by: java.lang.IllegalArgumentException: World cannot be null
05.08 15:45:42 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
05.08 15:45:42 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.createMap(CraftServer.java:1705) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:42 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.createMap(CraftServer.java:248) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:45:42 [Server] INFO at org.bukkit.Bukkit.createMap(Bukkit.java:859) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
05.08 15:45:42 [Server] INFO at fr.lezoo.stonks.display.board.Board$BoardPoint.fillItemFrame(Board.java:371) ~[Stonks-1.0.4.jar:?]
05.08 15:45:42 [Server] INFO at fr.lezoo.stonks.display.board.Board$BoardPoint.createItemFrame(Board.java:362) ~[Stonks-1.0.4.jar:?]
05.08 15:45:42 [Server] INFO at fr.lezoo.stonks.display.board.Board.checkItemFrames(Board.java:200) ~[Stonks-1.0.4.jar:?]
05.08 15:45:42 [Server] INFO at fr.lezoo.stonks.display.board.Board.initializeBoard(Board.java:95) ~[Stonks-1.0.4.jar:?]
05.08 15:45:42 [Server] INFO at fr.lezoo.stonks.display.board.Board.<init>(Board.java:65) ~[Stonks-1.0.4.jar:?]
05.08 15:45:42 [Server] INFO at fr.lezoo.stonks.command.nodes.display.board.CreateTreeNode.execute(CreateTreeNode.java:89) ~[Stonks-1.0.4.jar:?]
05.08 15:45:42 [Server] INFO at fr.lezoo.stonks.command.objects.CommandTreeRoot.onCommand(CommandTreeRoot.java:40) ~[Stonks-1.0.4.jar:?]
05.08 15:45:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]

And the output when creating a map:

> 05.08 15:46:44 [Server] INFO supermidas issued server command: /stonks display map create ahjin day 3 3
05.08 15:46:44 [Server] ERROR null
05.08 15:46:44 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'stonks' in plugin Stonks v1.0.4
05.08 15:46:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
05.08 15:46:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
05.08 15:46:44 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:44 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:44 [Server] INFO at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.1.jar:?]
05.08 15:46:44 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
05.08 15:46:44 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:290) ~[?:?]
05.08 15:46:44 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2295) ~[?:?]
05.08 15:46:44 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2249) ~[?:?]
05.08 15:46:44 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
05.08 15:46:44 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
05.08 15:46:44 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:44 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
05.08 15:46:44 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
05.08 15:46:44 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:44 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:44 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
05.08 15:46:47 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:47 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:47 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
05.08 15:46:47 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:47 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:47 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
05.08 15:46:47 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
05.08 15:46:47 [Server] INFO Caused by: java.lang.IllegalArgumentException: No stock found with ID 'create'
05.08 15:46:47 [Server] INFO at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[commons-lang-2.6.jar:2.6]
05.08 15:46:47 [Server] INFO at fr.lezoo.stonks.manager.StockManager.get(StockManager.java:94) ~[Stonks-1.0.4.jar:?]
05.08 15:46:47 [Server] INFO at fr.lezoo.stonks.command.nodes.display.MapTreeNode.execute(MapTreeNode.java:28) ~[Stonks-1.0.4.jar:?]
05.08 15:46:47 [Server] INFO at fr.lezoo.stonks.command.objects.CommandTreeRoot.onCommand(CommandTreeRoot.java:40) ~[Stonks-1.0.4.jar:?]
05.08 15:46:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]

Please let me know if you need additional information.

**Comment by Guillaumemartinfesta** [comment]
I just tested this on 1.19.1 and I don't have any bugs. Did you find out the problem ?

**Comment by Guillaumemartinfesta** [comment]
The second bug is due to this:
05.08 15:46:47 [Server] INFO Caused by: java.lang.IllegalArgumentException: No stock found with ID 'create'.
You must not say create for maps just directly the id. 
I will make a good error message for this tho.

**Comment by Guillaumemartinfesta** [comment]
Okay found what was the problem for the first one too and fixed it!
