### ISSUE TITLE
Leverage 

### ISSUE THREAD

**Issue by Hariotiki** [le-zoo/stonks#6]
hello.
 when I take orders with leverage effects. when I am in loss, it regularly happens that the loss is greater than my initial sum, and the order is not cut. (buy $5000 a share, with leverage 5, I am at -46000 and the order does not close automatically at -5000). Thanks for your help

**Comment by Guillaumemartinfesta** [comment]
In the config.yml file there is a line share-refresh-time, this is the time at which Stonks check if your order should be cut. By default it is at 60 but you can decrease to maybe 1 or 2 to cut directly your order when it is negative ;). Sorry for the long response time as there are not a lot of ppl on Stonks and all the other projects are on gitlab I'm not looking very frequently. Feel free to ask on the discord if you have other questions ;)
